name: 构建和发布

on:
  workflow_dispatch:
    inputs:
      version:
        description: '版本号 (例如: v1.0.0)'
        required: true
        default: 'v1.0.0'
      prerelease:
        description: '是否为预发布版本'
        type: boolean
        default: false
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v3
    
    - name: 设置 Python 环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    
    - name: 创建 spec 文件
      run: |
        echo "# -*- mode: python ; coding: utf-8 -*-

        block_cipher = None

        a = Analysis(
            ['subtitle_to_speech.py'],
            pathex=[],
            binaries=[],
            datas=[('app.ico', '.')],
            hiddenimports=[],
            hookspath=[],
            hooksconfig={},
            runtime_hooks=[],
            excludes=[],
            win_no_prefer_redirects=False,
            win_private_assemblies=False,
            cipher=block_cipher,
            noarchive=False,
        )

        pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

        exe = EXE(
            pyz,
            a.scripts,
            a.binaries,
            a.zipfiles,
            a.datas,
            [],
            name='subtitle_to_speech',
            debug=False,
            bootloader_ignore_signals=False,
            strip=False,
            upx=True,
            upx_exclude=[],
            runtime_tmpdir=None,
            console=False,
            disable_windowed_traceback=False,
            target_arch=None,
            codesign_identity=None,
            entitlements_file=None,
            icon='app.ico'
        )" > subtitle_to_speech.spec
    
    - name: 构建可执行文件
      run: |
        pyinstaller subtitle_to_speech.spec
    
    - name: 获取版本号
      id: get_version
      shell: bash
      run: |
        if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
        else
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        fi
    
    - name: 创建发布版本
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.VERSION }}
        name: 发布版本 ${{ env.VERSION }}
        draft: false
        prerelease: ${{ github.event.inputs.prerelease || false }}
        files: |
          ./dist/subtitle_to_speech.exe
        body: |
          # 字幕转语音工具 ${{ env.VERSION }}
          
          ## 更新内容
          - 支持 SRT 和 ASS 字幕文件转换为语音
          - 支持多种中文语音选择
          - 支持视频配音和背景音乐混合
          - 实时预览语音效果
          
          ## 安装说明
          1. 下载 subtitle_to_speech.exe
          2. 确保系统已安装 FFmpeg（[下载地址](https://www.gyan.dev/ffmpeg/builds/)）
          3. 运行程序即可使用
          
          ## 注意事项
          - 需要网络连接以使用语音服务
          - 转换大文件可能需要较长时间
          - 建议先试听语音效果再进行转换
          
          ## 反馈问题
          如果遇到问题，请在 Issues 中反馈，并提供以下信息：
          - 系统环境
          - 具体错误信息
          - 重现步骤